version: "2.1"
services:
  ytdlp2strm:
    build: .
    #image: fe80grau/ytdlp2strm
    container_name: ytdlp2strm
    environment:
      - AM_I_IN_A_DOCKER_CONTAINER=Yes
      - DOCKER_PORT=5005
      - TZ=America/Chicago
    volumes:
      - /media:/media
      - ./plugins/youtube/channel_list.json:/opt/ytdlp2STRM/plugins/youtube/channel_list.json
      - ./plugins/youtube/config.json:/opt/ytdlp2STRM/plugins/youtube/config.json
      - ./config/config.json:/opt/ytdlp2STRM/config/config.json
      - ./config/crons.json:/opt/ytdlp2STRM/config/crons.json
      - ./ytdlp2strm.log:/opt/ytdlp2STRM/ytdlp2strm.log
      - ./cookies.txt:/opt/ytdlp2STRM/cookies.txt
    ports:
      - 5005:5005
    restart: always
    networks:
      - media

networks:
  media:
    external: true
